services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # We use 'db' as the hostname because it matches the service name below
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/soukDB
      SPRING_DATASOURCE_USERNAME: ahmed
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:17
    container_name: postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ahmed -d soukDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: soukDB
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgresdata:
