#spring.application.name=demo
# PostgreSQL connection
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/soukDB
spring.datasource.username=ahmed
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000

logging.level.root=INFO


logging.level.souk.demo=DEBUG

# Save logs to a file
logging.file.name=logs/app.log



